-- Jackson Goyette, Spencer Schurk
-- Lab 2, CSC 365, CARS dataset

CREATE TABLE CARMAKERS(
	ID INTEGER PRIMARY KEY UNIQUE,
	MAKER CHAR(10),
	FULLNAME CHAR (30),
	COUNTRY INTEGER REF COUNTRIES(COUNTRYID),
--	FOREIGN KEY(COUNTRY) REFERENCES COUNTRIES(COUNTRYID));

CREATE TABLE CARNAMES(
	MAKEID INTEGER PRIMARY KEY UNIQUE,
	MODEL CHAR(30) REF MODELLIST(MODEL),
--	FOREIGN KEY(MODEL) REFERENCES MODELLIST(MODEL),
	MAKEDESCRIPTION CHAR(60));

CREATE TABLE CARSDATA(
	ID INTEGER PRIMARY KEY UNIQUE REF CARNAMES(MAKEID),
--	FOREIGN KEY ID REFERENCES CARNAMES(MAKEID),
	MPG FLOAT,
	CYLINDERS INTEGER,
	EDISPL FLOAT,
	HORSEPOWER FLOAT,
	WEIGHT FLOAT,
	ACCELERATE FLOAT,
	YEAR INTEGER);

CREATE TABLE CONTINENTS(
	CONTID INTEGER PRIMARY KEY UNIQUE,
	CONTINENT CHAR(30));

CREATE TABLE COUNTRIES(
	COUNTRYID INTEGER PRIMARY KEY UNIQUE,
	COUNTRY NAME CHAR(30),
	CONTINENT INTEGER REF CONTINENTS(CONTID));

CREATE TABLE MODELLIST(
	MODELID INTEGER PRIMARY KEY UNIQUE,
	MAKER INTEGER REF CARMAKERS(ID),
	MODEL CHAR(30) UNIQUE);
