-- Jack Goyette, Spencer Schurk
-- jgoyette@calpoly.edu, sschurk@calpoly.edu

SELECT * FROM CARMAKERS;
SELECT COUNT(*) FROM CARMAKERS;

SELECT * FROM CARNAMES;
SELECT COUNT(*) FROM CARNAMES;

SELECT * FROM CARSDATA;
SELECT COUNT(*) FROM CARSDATA;

SELECT * FROM CONTINENTS;
SELECT COUNT(*) FROM CONTINENTS;

SELECT * FROM COUNTRIES;
SELECT COUNT(*) FROM COUNTRIES;

SELECT * FROM MODELLIST;
SELECT COUNT(*) FROM MODELLIST;
