CREATE TABLE CAMPUSES (
    ID INT PRIMARY KEY,
    CAMPUS CHAR(60),
    LOC CHAR(60),
    COUNTY CHAR(60),
    YEAR INT
);

CREATE TABLE CSU_FEES (
    CAMPUS INT REFERENCES CAMPUSES(ID),
    YEAR INT,
    CAMPUS_FEE INT
);