-- Jack Goyette, Spencer Schurk
-- jgoyette@calpoly.edu, sschurk@calpoly.edu

DROP TABLE CAMPUSES;

DROP TABLE CSU_FEES;

DROP TABLE DEGREES;

DROP TABLE DISCIPLINE_ENROLLMENTS;

DROP TABLE DISCIPLINES;

DROP TABLE ENROLLMENTS;

DROP TABLE FACULTY;
