-- Jack Goyette, Spencer Schurk
-- jgoyette@calpoly.edu, sschurk@calpoly.edu


CREATE TABLE CAMPUSES (
    ID INT PRIMARY KEY,
    CAMPUS CHAR(60),
    LOC CHAR(60),
    COUNTY CHAR(60),
    YEAR INT
);

CREATE TABLE CSU_FEES (
    CAMPUS INT REFERENCES CAMPUSES(ID),
    YEAR INT,
    CAMPUS_FEE INT
);

CREATE TABLE DEGREES (
    YEAR INT,
    CAMPUS INT REFERENCES CAMPUSES(ID),
    DEGREES INT
);

CREATE TABLE DISCIPLINE_ENROLLMENTS (
    CAMPUS INT REFERENCES CAMPUSES(ID),
    DISCIPLINE INT REFERENCES DISCIPLINES(ID),
    YEAR INT,
    UNDERGRADUATE INT,
    GRADUATE INT
);

CREATE TABLE DISCIPLINES (
    ID INT PRIMARY KEY,
    NAME CHAR (60)
);

CREATE TABLE ENROLLMENTS (
    CAMPUS INT REFERENCES CAMPUSES(ID),
    YEAR INT,
    TOTAL_ENROLLMENT_AY INT,
    FTE_AY INT
);

CREATE TABLE FACULTY (
    CAMPUS INT REFERENCES CAMPUSES(ID),
    YEAR INT,
    FACULTY INT
);
