-- Jackson Goyette, Spencer Schurk
-- Lab 2, CSC 365, MARATHON

CREATE TABLE MARATHON(
	PLACE INTEGER PRIMARY KEY UNIQUE,
	TIME CHAR(8),
	PACE CHAR(5),
	GROUPPLACE INTEGER UNIQUE,
	GROUP CHAR(5),
	AGE INTEGER,
	SEX CHAR(1),
	BIBNUMBER INTEGER,
	FIRSTNAME CHAR(20),
	LASTNAME CHAR(20),
	TOWN CHAR(30),
	STATE CHAR(2));
